apiVersion: apps/v1
kind: Deployment
metadata:
  name: "testdeploy"
  labels:
    app: "testpo"

spec:
  replicas: 2
  selector:
    matchLabels:
      app: testpo
  template:
     metadata:
      labels:
        app: testpo
     spec:
      volumes:
      - name: mypod-pvc
        persistentVolumeClaim:
         claimName: mypvc
      containers:
      - name: "testcon1"
        image: "deepakdocker25/dockerapp"
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: mypod-pvc

      nodeSelector:
          ip-10-0-1-171.ap-south-1.compute.internal: ip-10-0-1-171.ap-south-1.compute.internal
