apiVersion: apps/v1
kind: Deployment
metadata:
  name: "testdeploy"
  labels:
    app: "testpo"

spec:
  replicas: 2
  selector:
    matchLabels:
      app: testpo
  template:
     metadata:
      labels:
        app: testpo
     spec:
      containers:
      - name: "testcon1"
        image: "deepakdocker25/dockerapp"


      nodeSelector:
          node-name: ip-10-0-1-171.ap-south-1.compute.internal
